language: generic 
sudo: required
services:
  - docker

before-install:
  - docker build -t imadityasinha/docker-react -f Dockerfile.dev .

script:
  docker run imadityasinha/docker-react npm run test -- --coverage
