language: generic 
sudo: required
services:
  - docker

before-install:
  - docker build -t imadityasinha/docker-react -f Dockerfile.dev .

script:
  docker run -e CI=true imadityasinha/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-461171328690"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
